name: cellpose-gui
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.5.0
  - fontconfig=2.14.2
  - freetype=2.12.1
  - gds-tools=1.7.2.10
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - intel-openmp=2022.1.0
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - lz4-c=1.9.4
  - magma=2.7.1
  - markupsafe=2.1.3
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mysql=5.7.24
  - nccl=2.19.3.1
  - ncurses=6.4
  - nsight-compute=2023.2.2.3
  - nspr=4.35
  - nss=3.89.1
  - numba=0.57.1
  - numpy=1.24.4
  - openssl=3.1.3
  - packaging=23.1
  - pcre=8.45
  - pcre2=10.40
  - pip=23.2.1
  - ply=3.11
  - pyqt=5.15.7
  - python=3.10.0
  - python_abi=3.10
    # - pytorch=2.1.2
  - pytorch-cuda=11.8
    # - pytorch-gpu
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scipy=1.11.3
  - setuptools=68.0.0
  - sip=6.6.2
  - sleef=3.5.1
  - sqlite=3.41.2
  - tbb=2021.9.0
  - tk=8.6.12
  - typing_extensions=4.8.0
  - tzdata=2023c
  - wheel=0.41.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cachetools==5.3.1
      - cellpose==2.2.3
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - fastremap==1.14.0
      - filelock==3.12.4
      - fsspec==2023.9.2
      - google-api-core==2.12.0
      - google-auth==2.23.2
      - google-cloud-core==2.3.3
      - google-cloud-storage==2.11.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.6.0
      - googleapis-common-protos==1.60.0
      - idna==3.4
      - imagecodecs==2023.9.18
      - jinja2==3.1.2
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.2
      - opencv-python-headless==4.8.1.78
      - protobuf==4.24.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.16.1
      - pyqt5-sip==12.11.0
      - pyqtgraph==0.13.3
      - qtpy==2.4.0
      - requests==2.31.0
      - roifile==2023.8.30
      - rsa==4.9
      - superqt==0.6.0
      - sympy==1.12
      - tifffile==2023.9.26
      - toml==0.10.2
      - tqdm==4.66.1
      - typing-extensions==4.8.0
      - urllib3==2.0.6
